development:
  adapter: mysql
  database: cf2010_dev
  username: root
  password: thibamay
  host: localhost

test:
  adapter: mysql
  database: cf2010_test
  username: root
  password: thibamay
  host: localhost

production:
  adapter: mysql
  database: cf2010
  username: root
  password: 
  host: localhost
