development:
  adapter: mysql
  database: cf_dev
  username: root
  password: 
  host: localhost

test:
  adapter: mysql
  database: cf_test
  username: root
  password: 
  host: localhost

production:
  adapter: mysql
  database: cf
  username: root
  password: thibamay
  host: localhost
